/**
 * Extracts the Avro fuzzy-search pattern table and the suffix table from the
 * upstream ibus-avro sources (vendor/ibus-avro, MPL-2.0) into typed modules
 * under src/suggest/data/. Run again only when the vendor files change:
 *
 *   npx tsx scripts/extract-avro-data.ts
 *
 * The upstream files are evaluated in an isolated VM context; nothing from
 * them runs in the extension itself.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { runInNewContext } from 'node:vm';

const root = resolve(import.meta.dirname, '..');
const vendor = join(root, 'vendor/ibus-avro');
const outDir = join(root, 'src/suggest/data');

const MPL_HEADER = (original: string, authors: string) => `/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Data extracted from ${original} of ibus-avro (https://github.com/sarim/ibus-avro).
 * The Original Code is jsAvroPhonetic. ${authors}
 * Copyright (C) OmicronLab (http://www.omicronlab.com). All Rights Reserved.
 *
 * GENERATED by scripts/extract-avro-data.ts. Do not edit by hand.
 */
`;

interface RawMatch {
  type: string;
  scope: string;
  value?: string;
  negative?: string | boolean;
}
interface RawPattern {
  find: string;
  replace: string;
  rules?: Array<{ matches: RawMatch[]; replace: string }>;
}
interface RawData {
  patterns: RawPattern[];
  vowel: string;
  consonant: string;
  ignore: string;
}

export function readRegexData(): RawData {
  const sandbox: { AvroRegex?: { prototype: { data: RawData } } } = {};
  const src = readFileSync(join(vendor, 'avroregexlib.js'), 'utf8').replace(/^const utfconv = imports\.utf8;$/m, '');
  runInNewContext(`${src}\n;this.AvroRegex = AvroRegex;`, sandbox);
  const data = sandbox.AvroRegex?.prototype.data;
  if (!data) throw new Error('could not read AvroRegex data');
  return data;
}

export function readSuffixData(): Record<string, string> {
  const sandbox: { db?: Record<string, string> } = {};
  runInNewContext(`${readFileSync(join(vendor, 'suffixdict.js'), 'utf8')}\n;this.db = db;`, sandbox);
  if (!sandbox.db) throw new Error('could not read suffix data');
  return sandbox.db;
}

/** Upstream writes negative:"FALSE" (a truthy string that acts as false under XOR). Normalize to booleans. */
function normalizeNegative(m: RawMatch): { scope: string; negative: boolean } {
  let scope = m.scope;
  let negative = m.negative === true || m.negative === 'TRUE';
  if (scope.startsWith('!')) {
    negative = true;
    scope = scope.slice(1);
  }
  return { scope, negative };
}

function main(): void {
  mkdirSync(outDir, { recursive: true });
  const data = readRegexData();
  const patterns = data.patterns.map((p) => ({
    find: p.find,
    replace: p.replace,
    rules: (p.rules ?? []).map((r) => ({
      replace: r.replace,
      matches: r.matches.map((m) => ({ type: m.type, value: m.value ?? '', ...normalizeNegative(m) })),
    })),
  }));
  const regexTs =
    MPL_HEADER('avroregexlib.js', 'Initial Developers: Mehdi Hasan Khan, Rifat Nabi.') +
    `import type { RegexData } from '../avroRegex';\n\n` +
    `export const REGEX_DATA: RegexData = ${JSON.stringify(
      { patterns, vowel: data.vowel, consonant: data.consonant, ignore: data.ignore },
      null,
      1,
    )};\n`;
  writeFileSync(join(outDir, 'regexData.ts'), regexTs);

  const suffix = readSuffixData();
  const suffixTs =
    MPL_HEADER('suffixdict.js', 'Initial Developer: Mehdi Hasan Khan.') +
    `/** English suffix -> Bangla suffix. */\n` +
    `export const SUFFIXES: Readonly<Record<string, string>> = ${JSON.stringify(suffix, null, 1)};\n`;
  writeFileSync(join(outDir, 'suffixData.ts'), suffixTs);
  console.log(`wrote ${patterns.length} patterns and ${Object.keys(suffix).length} suffixes to src/suggest/data/`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
